FROM python:3.7.5-slim-buster
MAINTAINER Oscar Rubio Garcia 
WORKDIR /code

RUN apt update && apt upgrade

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD . .

CMD [ "gunicorn", "-b", "0.0.0.0:5000", "app:api", "--reload" ]