FROM alpine:latest
MAINTAINER Oscar Rubio Garcia 

WORKDIR /code

RUN apk update && apk upgrade
RUN apk add --no-cache --update \
	linux-headers \
    git \
    bash \
    libffi-dev \
    openssl-dev \
    bzip2-dev \
    zlib-dev \
    readline-dev \
    sqlite-dev \
    build-base

# Set Python version
ARG PYTHON_VERSION='3.7.0'
# Set pyenv home
ARG PYENV_HOME=/root/.pyenv

# Install pyenv, then install python versions
RUN git clone --depth 1 https://github.com/pyenv/pyenv.git $PYENV_HOME && \
    rm -rfv $PYENV_HOME/.git

ENV PATH $PYENV_HOME/shims:$PYENV_HOME/bin:$PATH

RUN pyenv install $PYTHON_VERSION
RUN pyenv global $PYTHON_VERSION
RUN pip install --upgrade pip && pyenv rehash

# Clean
RUN rm -rf ~/.cache/pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /code

CMD [ "gunicorn", "-b", "0.0.0.0:5000", "app:api", "--reload" ]

