FROM python:3.7-alpine
MAINTAINER Oscar Rubio Garcia 
WORKDIR /code

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /code

CMD [ "gunicorn", "-b", "0.0.0.0:5000", "app:api", "--reload" ]